- name: Fist example deploy with Ansible AWX
  hosts: all
  tasks:
#     - name: Permission denied file shell 
#       command: docker build .
     
    - name: Transfer REPO the script
      command: sh  /var/www/pemaza_vendas/rundockerized.sh
      
#     - name: Execute shell to deploy with docker-compose
#       command: sh rundockerized.sh
