---
- name: Deploy
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: create directory app
      become: yes
      file: path=/volumes/erp/client state=directory

    - name: Deploy (Git)
      become: yes
      git:
         repo: "https://github.com/wagneroliveira/client.git"
         dest: /volumes/erp/client
         force: yes
         
    - name: Install dependencies
      become: yes
      npm:
        path: "/volumes/erp/client"

    # Build para gerar o dist
    - name: Build project compras to generate dist
      command: npm run build
      args:
        chdir: "/volumes/erp/client"

         
#     - name: Running NPM install
#       npm: path={{homeDir}}/{{appDir}}/backened
#       register: npm_finished
#       when: git_finished.changed

#     - name: Execute script to docker-compose
#       command: docker-compose -f /var/lib/awx/ansible/client-test/docker-compose.yml up -d
#       command: sh ~/ansible/client-test/rundockerized.sh
#       command: npm install

...

