---
- name: Deploy
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: create directory app
      file: path=~/ansible/client-test/ state=directory

    - name: Deploy (Git)
      git:
         repo: "https://github.com/wagneroliveira/client.git"
         dest: ~/ansible/client-test
         force: yes

    - name: Execute script to docker-compose
      command: docker-compose -f /var/lib/awx/ansible/client-test/docker-compose.yml up -d
#       command: sh ~/ansible/client-test/rundockerized.sh

...

